project_id = "rytqivfvmbznhnzkjwne"

[functions.telegram-webhook]
verify_jwt = false

[functions.analytics-ai]
verify_jwt = false

[functions.upload-to-telegram]
verify_jwt = false

[functions.channel-ai]
verify_jwt = false

[functions.manage-subscriptions]
verify_jwt = false

[functions.content-manager]
verify_jwt = false
